version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: src/External/Public/Tourism.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=Tourism;User Id=sa;Password=YourStrong@Password;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"